#!/bin/sh

activate_virtual_environment() {
  #
  # Activates virtual environment in the cwd
  #

  activate_path=`find . -maxdepth 3 -path "*/bin/activate" -type f`

  [ "$activate_path" = '' ] && echo 'No environment to activate.' && return 1

  source $activate_path
  return 0
}

tmux() {
  #
  # Wraps tmux
  #

  # If called with args, continue straight to tmux
  if [[ -n "$@" ]]; then
    command tmux "$@"
    return
  fi

  # Reconstructs the project's tmux session or creates new one
  if [ -x .tmux ]; then
    ./.tmux
    return
  fi

  local session_name=$(basename $(pwd))
  command tmux new-session -A -s "$session_name"
}

directory() {
  #
  # Quickly navigate to a folder with fzf
  #

  cd $(find . -type d 2>/dev/null | fzf)
}

edit-file() {
  #
  # Quickly edit a file with fzf
  #

  file=$(find . -type f 2>/dev/null | fzf )

  if [ -z "$file" ] ; then
    return
  fi

  nvim $file
}
