#! /bin/sh -eu

# Where the source code is.
# SRC_DIR=~/.local/src/xmonad/
# # The name of executable in cabal file
# EXE_NAME=xmonad

# OUTPUT_D="$(dirname $1)"
# OUTPUT_F="$(basename $1)"

# cd $SRC_DIR

# exec ghc --make ~/.config/xmonad/xmonad.hs -i -ilib -main-is main -fforce-recomp -v0 -o "$1"
#
cd ~/.local/src/xmonad_config

out_dir=$(dirname $1)
out_file=$(basename $1)
exe_name="xmonad-x86_64-linux"
echo "$1" > ~/build_dest

cabal install exe:"$exe_name" \
  --installdir "$out_dir" \
  --overwrite-policy=always \
  --enable-executable-stripping \
  --enable-optimization=2

if [ "$exe_name" != "$out_file" ] ; then
  ln -sf "$exe_name" "$1"
fi
