[[item]]
file = '~/.config/alacritty/theme.toml'
template = 'alacritty'
subtemplate = 'default-256'
rewrite = true

[[item]]
file = '~/.config/nvim/after/plugin/theme.lua'
template = 'nvim'
rewrite = true

# [[item]]
# file = '~/.config/rofi/colors.rasi'
# template = 'rofi'
# subtemplate = 'colors'
# rewrite = true
